#!/usr/bin/env python3
"""Subset the committed Libertinus fonts to WOFF2 (TYPE-8).

The character set is every character in the site's sources (Pollen markup,
template, Racket) plus a fixed base set, so the build never needs the
rendered HTML first and the files only change when the text does. Output
names carry a content hash; assets/fonts/fonts.rktd maps each face to its
URL for the template.

Run from the repository root: python3 tools/fonts.py
"""

import hashlib
import io
import pathlib
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = ROOT / "assets" / "fonts"
MANIFEST = FONTS / "fonts.rktd"

# key -> source file. Order matters only for the manifest.
FACES = {
    "serif-regular": "LibertinusSerif-Regular.otf",
    "serif-italic": "LibertinusSerif-Italic.otf",
    "serif-semibold": "LibertinusSerif-Semibold.otf",
    "mono-regular": "LibertinusMono-Regular.otf",
}

# Always included: printable ASCII, Latin-1, the punctuation and spaces the
# typography rules and smart quotes produce, and common symbols.
BASE = (
    set(range(0x20, 0x7F))
    | set(range(0xA0, 0x100))
    | set(range(0x2009, 0x200B))  # thin, hair space
    | set(range(0x2010, 0x2027))  # dashes, quotes, bullets, ellipsis
    | set(range(0x2030, 0x203B))  # per mille, primes, angle quotes
    | {0x2060, 0x202F, 0x00D7, 0x2212, 0x2042, 0x2261}
    | set(range(0x2190, 0x219A))  # arrows
)

# OpenType features the CSS uses. Everything else (stylistic sets, dlig,
# frac, sups…) is dropped to keep the three text faces under 120 KB (§14).
FEATURES = [
    "kern", "liga", "clig", "calt", "ccmp", "locl", "mark", "mkmk", "case",
    "smcp", "c2sc", "onum", "lnum", "pnum", "tnum",
]

SOURCE_GLOBS = ["**/*.pm", "**/*.p", "*.rkt", "lib/*.rkt", "**/*.svg", "**/*.csv", "data/*.json"]
SKIP_DIRS = {"public", "compiled", ".git", "node_modules"}


def source_chars():
    chars = set()
    for pattern in SOURCE_GLOBS:
        for path in ROOT.glob(pattern):
            if SKIP_DIRS & set(path.relative_to(ROOT).parts):
                continue
            chars |= {ord(c) for c in path.read_text(encoding="utf-8")}
    return {c for c in chars if c >= 0x20}


def subset_face(src, unicodes):
    font = TTFont(src)
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = FEATURES
    options.name_IDs = ["*"]  # keep copyright and licence names (OFL)
    options.notdef_outline = True
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    return buf.getvalue()


def main():
    unicodes = sorted(BASE | source_chars())
    for old in FONTS.glob("*.woff2"):
        old.unlink()
    entries = []
    total = 0
    for key, name in FACES.items():
        data = subset_face(FONTS / name, unicodes)
        digest = hashlib.sha256(data).hexdigest()[:10]
        out = FONTS / f"{pathlib.Path(name).stem}.{digest}.woff2"
        out.write_bytes(data)
        total += len(data)
        entries.append(f'  ({key} . "/assets/fonts/{out.name}")')
        print(f"fonts: {out.name} {len(data) / 1024:.1f} KB")
    MANIFEST.write_text(
        ";; Generated by tools/fonts.py; do not edit.\n(\n" + "\n".join(entries) + "\n)\n",
        encoding="utf-8",
    )
    print(f"fonts: {len(unicodes)} code points, {total / 1024:.1f} KB in total")


if __name__ == "__main__":
    sys.exit(main())
